apiVersion: v1
kind: Template
metadata:
  name: hac-dev
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: Frontend
  metadata:
    name: hac-dev
  spec:
    API:
      versions:
        - v1
    assetsPrefix: api/plugins
    deploymentRepo: 'http://test'
    envName: ephem-hac
    frontend:
      paths:
        - /api/plugins/hac-dev
        - /apps/hac-dev
    image: ${IMAGE}:${IMAGE_TAG}
    title: hac-dev
    module:
      manifestLocation: /apps/hac-dev/fed-mods.json
      moduleID: hacDev
      modules:
        - id: hacDev
          module: ./RootApp
          routes:
            - pathname: /hac/app-studio
    navItems:
      - appId: hacDev
        href: /hac/app-studio
        product: Red Hat Insights
        title: App Studio
parameters:
  - name: IMAGE_TAG
    value: latest
  - name: IMAGE
    value: quay.io/cloudservices/hac-dev-frontend
